apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositecontrollers.{{ .Values.crd.group }}
  labels:
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}
    helm.sh/chart: {{ include "metacontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: {{ .Values.crd.group }}
  version: {{ .Values.crd.version }}
  scope: {{ .Values.crd.scope }}
  names:
    plural: compositecontrollers
    singular: compositecontroller
    kind: CompositeController
    shortNames:
    - cc
    - cctl
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decoratorcontrollers.{{ .Values.crd.group }}
  labels:
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}
    helm.sh/chart: {{ include "metacontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: {{ .Values.crd.group }}
  version: {{ .Values.crd.version }}
  scope: {{ .Values.crd.scope }}
  names:
    plural: decoratorcontrollers
    singular: decoratorcontroller
    kind: DecoratorController
    shortNames:
    - dec
    - decorators
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllerrevisions.{{ .Values.crd.group }}
  labels:
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}
    helm.sh/chart: {{ include "metacontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: {{ .Values.crd.group }}
  version: {{ .Values.crd.version }}
  scope: {{ .Values.crd.scope }}
  names:
    plural: controllerrevisions
    singular: controllerrevision
    kind: ControllerRevision
