name: Lint Charts

on:
  pull_request:
    branches:
      - dev

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run chart-testing (lint) ${{ github.ref }} against dev
      id: lint
      uses: helm/chart-testing-action@v1.0.0-alpha.3
      with:
        command: lint
        config: .github/actions/chart-testing/config-dev.yaml

